### ISSUE TITLE
2FA Account Login Failures

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#18]
**Describe the bug**
2FA logins always fail in app on Android when using correct details

**To Reproduce**
1. Install app
2. Access App Info in System Settings
3. Clear data and cache (ensures no login cache)
4. Open app
5. Attempt to login
6. Generate Authy code
7. Enter Authy code
8. Attempt login
9. Login will fail

**Expected behavior**
Login success with access to playlists from account. 

**Screenshots**

![Screenshot-1_20200105-133733](https://user-images.githubusercontent.com/59532240/71781041-f8f1a100-2fc1-11ea-997d-1c62934cd786.jpg)

![Screenshot-2_20200105-133801](https://user-images.githubusercontent.com/59532240/71781040-f8590a80-2fc1-11ea-8ef9-467906f8316c.jpg)

![Screenshot-3_20200105-133745](https://user-images.githubusercontent.com/59532240/71781043-f8f1a100-2fc1-11ea-9c99-e736290c2447.jpg)

**Smartphone:**
 - Device: Samsung Note9 (Qualcomm Dual SIM)
 - OS: Android 9 December 2019 Patch

![Screenshot-SysInfo_20200105-134016](https://user-images.githubusercontent.com/59532240/71781042-f8f1a100-2fc1-11ea-8831-fa600ed1915e.jpg)

 - Browser: Vivaldi
 - Version: 2.9.1741.39

**Comment by lucaspape** [comment]
I will look into that, I am reworking the authentication anyway.

**Comment by lucaspape** [comment]
I think I finally fixed it now. I tested it and it worked, I will test it a bit more later and then close this issue.

**Comment by lucaspape** [comment]
Tested it again and it worked. Fixed in 0.0.8.0
