### ISSUE TITLE
"Play Next" on playlist causes crash

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#19]
**Describe the bug**
Trying to "play next" a playlist causes entire so process to crash. 

**To Reproduce**
1. Go to playlists
2. Press and hold on a playlist
3. Press "Play Next"
4. Crash

**Expected behavior**
Ideally there would be a button to play a playlist. Expected behaviour from play next button is that playlist gets queued, either playing immediately or after currently playing song. Playing a song from within the playlist assists to work through the playlist, but have not tested extensively. 

**Screenshots**

[Video of crash](http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200105_211136.mp4) 

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: Android 9
 - Browser: Vivaldi 
 - Version: MCP beta 0.0.8.0

**Additional context**
Issue has existed in all previously tested builds

**Comment by lucaspape** [comment]
Thank you, I totally forgot to implement this. It should be done now.

**Comment by lucaspape** [comment]
Fixed in 0.0.8.2

**Comment by flkrz** [comment]
Large playlists cause same crash as above, but with added bug of notification player not being killed when app crashes. 

Tested with a 55 track playlist https://www.monstercat.com/playlist/5d4478ceb1c2ce5727bd7e14

Screen capture of behaviour
http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200106_191919.mp4

**Comment by lucaspape** [comment]
I think it is probably already fixed. I want to add one more feature and then I will publish this version.

**Comment by lucaspape** [comment]
Please try it again with version 0.0.8.3, it is uploaded on github and should be on google play in half an hour.

**Comment by flkrz** [comment]
0.0.8.3 starts playing the first song of the playlist within a couple of seconds, no crashing.
