### ISSUE TITLE
Remember previous main app tab

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#20]
**Is your feature request related to a problem? Please describe.**
As demonstrated in the video from bug #19 , pressing the Android system navigation back button in the app when viewing a playlist returns to the default new tracks view, rather than the list of playlists. 

**Describe the solution you'd like**
Can the app be set to remember whether it was in the "Home" or "Playlist" view when using the back navigation button?

**Describe alternatives you've considered**
An in app back button of the same functionality (i.e. when viewing a playlist, a button to go back to the list of playlists would work)

**Additional context**
[Video from #19](http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200105_211136.mp4)

**Comment by lucaspape** [comment]
Yep this annoyed me as well. The solution is not amazing but it works.

**Comment by lucaspape** [comment]
Workaround in 0.0.8.2
