### ISSUE TITLE
2FA sessions do not persistent after app closed

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#22]
**Describe the bug**
App being closed for a while or crashes that require the app to be force stopped to properly recover cause the cached 2FA session to expire, requiring a new 2FA token session to be created. 

**To Reproduce**
1. Go to app settings
2. Go into catplayer settings
3. Force stop
4. Open app

**Expected behavior**
2FA session to persist longer than a day

**Screenshots**
First few seconds of http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200106_191919.mp4

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android 9
 - Browser: Catplayer / Vivaldi
 - Version: 0.0.8.2

**Additional context**
I will test this further with power saving settings disabled for the app. Ideally I wouldn't have to disable these, but for testing I can sacrifice some battery.

**Comment by lucaspape** [comment]
I am not sure why this is happening, I tried it with force closing the app and I did not need to create a new 2FA key.

**Comment by lucaspape** [comment]
Here my try: https://nextcloud.lucaspape.de/index.php/s/E5f54Qo5GLMZ5YR

**Comment by flkrz** [comment]
Yeah, I can't work out exactly what causes it. If it doesn't happen after the power saving is disabled on Samsung, then it would indicate the session data is reliant on the app remaining in memory in some way?

**Comment by lucaspape** [comment]
The Monstercat website uses a key for authentication that you get if you login. If 2FA is enabled this key has to be "verified" with the 2FA code (if the 2FA code is wrong you will still have the key but it won't work, at least I think that's how it works). The key is saved using Androids shared preferences which should be persistent and shouldn't conflict with any battery saving optimization, I also use it so save the settings.
Every time you open the app it loads the key and checks if it works properly, if it does not it performs a re-login.

**Comment by flkrz** [comment]
Update 0.0.8.3 has not yet come through on play store for me. Tried installing update manually from APK (failed). When opening app after, 2FA session had expired. App had not been used since this was reported (roughly 5 hours).

Also tested on a Google Pixel in the same timeline, same issue occurs.

**Comment by lucaspape** [comment]
For some reason the Google play store is taking a really long time today to process the update (most of the time it takes 20 minutes). I will check again for the 2FA issue on another device tomorrow. The reason the APK failed to install is probably because you tried updating it from the play store version, you can't update manually if you have the play store version installed and you also can't update the APK version from the play store.

**Comment by flkrz** [comment]
I'm aware of the APK / app store thing. I just hoped it would see the signatures and be ok. 

Oh well, I'll wait for the update to process and check again. I dear it may be a tough one to track down, which is a shame as the monstercat website doesn't have any issues with login persistence thanks to long life cookies.

**Comment by lucaspape** [comment]
Update should be out now (maybe only for alpha, not sure about beta)

**Comment by flkrz** [comment]
Just installed 0.0.8.3, opened app, 2FA prompted. 

Tested on both the Note 9 and the Google Pixel. 

Note 9 running Android 9, Pixel running Android 10.

**Comment by flkrz** [comment]
Have just updated to 0.1.0.2. Noticed on a previous build yesterday I was promoted for a 2FA code (but hadn't used the app for a few weeks, do cannot say if an issue for that). 

Following 0.1.0.2 install, credentials re-requested due to settings change. Will monitor to see if 2FA keeps prompting.

**Comment by lucaspape** [comment]
0.1.0.2 shouldn't do a difference, I think the problem is that I am only saving the "connect.sid" cookie, the main monstercat website also has some more cookies (for example "ajs_user_id:") which the connect.monstercat.com API does not provide and does not use. I think the api might invalidate the "connect.sid" if the main website is not called.

**Comment by lucaspape** [comment]
This is probably fixed now (since 1.0.8.1), I will have to wait until tomorrow to find out if it worked.

**Comment by lucaspape** [comment]
I am still logged in this morning with 2FA enabled, seems like it's finally working now.

**Comment by lucaspape** [comment]
I am still logged in this morning with 2FA enabled, seems like it's finally working now.

**Comment by flkrz** [comment]
Just updated to latest release and confirmed working.
