### ISSUE TITLE
Improve accessibility of object context menu

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#23]
**Is your feature request related to a problem? Please describe.**
Just a simple idea to improve UX and accessibility in the app. 

**Describe the solution you'd like**
Make the long press context menu that gives the options for download, play next etc accessible from a 3 dots menu button on the right edge of each object in a list. Gives a clearly defined and instantly recognisable way to see options for an object. 

**Describe alternatives you've considered**
This seems like the best option to me, but I'm more than happy to discuss. 

**Additional context**
Quick demo of feature as seen in YouTube app. 

http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200107_072959.mp4

**Comment by lucaspape** [comment]
Yep, that's done. Screenshot: 
![Screenshot_1578405112](https://user-images.githubusercontent.com/17984007/71900059-4ce4bd00-315d-11ea-8616-5b399692c100.png)

**Comment by lucaspape** [comment]
I have also changed the context menu to something like this, but I am not sure if this is better than the old one.
![Screenshot_1578405738](https://user-images.githubusercontent.com/17984007/71900786-caf59380-315e-11ea-9137-b4cd5caf23f2.png)

**Comment by lucaspape** [comment]
Should be done in [0.0.8.4](https://github.com/lucaspape/catplayer/releases/tag/0.0.8.4)
