### ISSUE TITLE
Playback thread becomes orphaned on single repeat playlist track

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#30]
**Describe the bug**
Play any track from a playlist and set it to loop repeat during playback.

The next task in sequence will be played by the main player thread, with a new thread being started to loop the track. The lord track cannot be stopped without force stopping the catplayer app. 

**To Reproduce**
1. Go to any playlist
2. Click on any song to play it
3. Set the song to loop repeat
4. Wait for song to end
5. Listen to 2 songs simultaneously. 

**Expected behavior**
The main playback thread to loop the track rather than spawning another thread

**Screenshots**
http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/Screen_Recording_20200501-113552.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 9
 - OS: Android Q / UI 2.0
 - Browser: Vivaldi
 - Version: 1.2.0.3

**Additional context**
Playback controls for shuffle etc very inconsistent.

**Comment by lucaspape** [comment]
Thank you for reporting this!
Should be fixed now, I will probably publish an update later this day.

**Comment by lucaspape** [comment]
Should be fixed since 1.2.0.4

**Comment by lucaspape** [comment]
This particular issue should be fixed but there is a similar one (also double playback), I currently have no time to do this because of life stuff and need to pause this project for a little bit, I can continue in about 1-2 Weeks

**Comment by lucaspape** [comment]
This issue didnt happen to me in a few months and I fixed a bug in https://github.com/lucaspape/catplayer/commit/aef6d3ae59e194c9926d4db971b3d7aeeb311d38 that could cause something like this, if it still happens reopen this issue
