### ISSUE TITLE
App volume resets when changing view

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#48]
**Describe the bug**
When changing app viewb(i.e. going back to the app via notifications, switching from now playing to other pages) the app volume will reset to 100. When opening settings, the customised value is reapplied. 

**To Reproduce**
1. Go to any view while music is playing
2. Click on a different view
3. Scroll down to playback volume should change
4. Go into app settings
5. Volume should automatically adjust back to custom value

**Expected behavior**
App volume remains consistent at all times

**Screenshots**

http://grail.rm-ni.uk:8080/static/git/cat/Screen_Recording_20210225-135311_Catplayer.mp4

**Smartphone (please complete the following information):**
 - Device: SAMSUNG NOTE 9
 - OS: ANDROID 10
 - Browser N/A
 - Version 1.6.2

**Comment by lucaspape** [comment]
Thank you, I just checked and I have this as well

**Comment by lucaspape** [comment]
Should be fixed with https://github.com/lucaspape/catplayer/commit/ec538f42ba1c3406817ed5afcaa95cda7ae462d1, I just used the wrong volume scale when initializing the player (which happens when switching activities)
