### ISSUE TITLE
No official playlists in Explore tab

### ISSUE THREAD

**Issue by Hinaxnitro** [lucaspape/catplayer#57]
In Monstercat web player's top page, there's a list of official playlists.
But there are no official playlists in the app.

**Comment by lucaspape** [comment]
Hi!
They aren’t there because I haven’t added them yet, I actually didn’t know that the official playlists are there too.
I’ll try to add them as soon as I can.

**Comment by lucaspape** [comment]
I added it in https://github.com/lucaspape/catplayer/commit/c24a1b6e9e6eda033046c4df622d8f87f6fa8fb2, its available in [1.7.0](https://github.com/lucaspape/catplayer/releases/tag/1.7.0) which is a pre-release right now. Should be in google play beta in a few hours.

**Comment by Hinaxnitro** [comment]
I checked that there are official playlists in the app.
Thank you.

2021年3月11日(木) 0:16 Lucas Pape ***@***.***>:
