### ISSUE TITLE
1.9.1 doesn't start

### ISSUE THREAD

**Issue by Hinaxnitro** [lucaspape/catplayer#79]
**Describe the bug**
New version (1.9.1) crashes at app's start up

**Screenshots**
![Screenshot_20210416-102636](https://user-images.githubusercontent.com/72604007/114959064-40dac580-9e9f-11eb-91bf-019b59e767d6.png)
![Screenshot_20210416-102651](https://user-images.githubusercontent.com/72604007/114959077-46d0a680-9e9f-11eb-9a52-bacb29fb57a4.png)

**Smartphone **
 - Device: SHARP AQUOS sense 3 plus
 - OS: Android 10
 - Browser Chrome Canary
 - Version 91.0.4469.5

**Comment by lucaspape** [comment]
Thank you for reporting, I fixed it here https://github.com/lucaspape/catplayer/commit/81baa2a9be3ec53dec55ce1fc0823577734e9bc0

**Comment by lucaspape** [comment]
I published it with [1.9.2](https://github.com/lucaspape/catplayer/releases/tag/1.9.2), if it still happens just reopen the issue
